# Generated by Django 4.0.5 on 2022-07-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_buyproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproduct',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
