# Generated by Django 4.0.5 on 2022-07-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_sellerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdata',
            name='product_id',
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='product_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.product'),
        ),
    ]
