# Generated by Django 4.0.5 on 2022-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0007_remove_sellerdata_product_id_sellerdata_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='product_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
