# Generated by Django 4.0.5 on 2022-07-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0008_alter_sellerdata_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='buyproduct',
            name='seller_name',
        ),
    ]
