# Generated by Django 4.0.5 on 2022-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0009_remove_buyproduct_buyer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='buy_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='seller_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
