# Generated by Django 4.0.5 on 2022-07-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0011_remove_buyproduct_buy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='buy_status',
            field=models.BooleanField(null=True),
        ),
    ]
