# Generated by Django 4.0.5 on 2022-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0012_buyproduct_buy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='seller_price',
            field=models.IntegerField(null=True),
        ),
    ]
